site_name: Puzzles

theme:
  name: material
  palette:
    primary: orange
    accent: deep orange

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
